FROM python:3.11-slim
WORKDIR /producer

RUN apt-get update && apt-get install -y --no-install-recommends build-essential && rm -rf /var/lib/apt/lists/*

COPY requirements.txt /producer/requirements.txt
RUN python -m pip install --upgrade pip && pip install -r /producer/requirements.txt

COPY kafka/producer.py /producer/producer.py
COPY backend /producer/backend_helpers

CMD ["python", "producer.py"]
